blank_issues_enabled: false
contact_links:
  - name: 📧 Email Support
    url: mailto:data-team@company.com
    about: Contact the data team directly for urgent issues
  - name: 💬 Internal Chat
    url: https://your-company-chat.com/data-team
    about: Quick questions and real-time support
